// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvkpwaiqlbrioymtqgam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2a3B3YWlxbGJyaW95bXRxZ2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTI2ODMsImV4cCI6MjA2NzIyODY4M30.VGmkbGqBn9k0ZOAqZPWVzQ-voE5KmCyokPWaVkdpbs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});